using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Vx.Generators;

[Generator]
public sealed class VxComponentParameterGenerator : IIncrementalGenerator
{
    private const string VxComponentMetadataName = "Vx.Views.VxComponent";
    private static readonly DiagnosticDescriptor ComponentMustBePartial = new(
        id: "VXGEN001",
        title: "Vx component must be partial",
        messageFormat: "Vx component '{0}' declares writable parameters and must be partial so parameter reconciliation can be generated",
        category: "Vx.Generators",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor ContainingTypeMustBePartial = new(
        id: "VXGEN002",
        title: "Containing type must be partial",
        messageFormat: "Containing type '{0}' must be partial so parameter reconciliation can be generated for nested Vx component '{1}'",
        category: "Vx.Generators",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var components = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is ClassDeclarationSyntax,
            static (generatorContext, _) => GetComponent(generatorContext))
            .Where(static component => component is not null)
            .Collect();

        context.RegisterSourceOutput(components, static (sourceContext, componentSymbols) =>
        {
            var generated = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            foreach (var component in componentSymbols)
            {
                if (component is not null && generated.Add(component))
                {
                    ProcessComponent(sourceContext, component);
                }
            }
        });
    }

    private static INamedTypeSymbol? GetComponent(GeneratorSyntaxContext context)
    {
        var declaration = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol type
            || type.ToDisplayString() == VxComponentMetadataName)
        {
            return null;
        }

        for (var baseType = type.BaseType; baseType is not null; baseType = baseType.BaseType)
        {
            if (baseType.ToDisplayString() == VxComponentMetadataName)
            {
                return type;
            }
        }

        return null;
    }

    private static void ProcessComponent(SourceProductionContext context, INamedTypeSymbol component)
    {
        var properties = component.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(static property => !property.IsStatic
                && !property.IsIndexer
                && property.DeclaredAccessibility == Accessibility.Public
                && property.SetMethod?.DeclaredAccessibility == Accessibility.Public)
            .OrderBy(static property => property.Locations.FirstOrDefault()?.SourceSpan.Start ?? int.MaxValue)
            .ToImmutableArray();

        if (properties.IsEmpty)
        {
            return;
        }

        if (component.GetMembers("ApplyParametersFrom")
            .OfType<IMethodSymbol>()
            .Any(static method => method.IsOverride))
        {
            return;
        }

        if (!IsPartial(component))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                ComponentMustBePartial,
                component.Locations.FirstOrDefault(),
                component.Name));
            return;
        }

        for (var containingType = component.ContainingType; containingType is not null; containingType = containingType.ContainingType)
        {
            if (!IsPartial(containingType))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    ContainingTypeMustBePartial,
                    containingType.Locations.FirstOrDefault(),
                    containingType.Name,
                    component.Name));
                return;
            }
        }

        GenerateComponent(context, component, properties);
    }

    private static void GenerateComponent(
        SourceProductionContext context,
        INamedTypeSymbol component,
        ImmutableArray<IPropertySymbol> properties)
    {

        var source = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        if (!component.ContainingNamespace.IsGlobalNamespace)
        {
            source.Append("namespace ").Append(component.ContainingNamespace.ToDisplayString()).Append("\n{\n");
        }

        var containingTypes = GetContainingTypes(component);
        foreach (var type in containingTypes)
        {
            source.Append("partial class ").Append(EscapeIdentifier(type.Name));
            if (type.TypeParameters.Length > 0)
            {
                source.Append('<').Append(string.Join(", ", type.TypeParameters.Select(static parameter => EscapeIdentifier(parameter.Name)))).Append('>');
            }
            source.Append("\n{\n");
        }

        source.Append("    protected override bool ApplyParametersFrom(global::Vx.Views.VxComponent source)\n")
            .Append("    {\n")
            .Append("        var newValues = (").Append(component.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(")source;\n")
            .Append("        var changed = base.ApplyParametersFrom(source);\n");

        foreach (var property in properties)
        {
            var name = EscapeIdentifier(property.Name);
            source.Append("        changed |= ApplyParameter(").Append(name).Append(", newValues.").Append(name)
                .Append(", value => ").Append(name).Append(" = value);\n");
        }

        source.Append("        return changed;\n")
            .Append("    }\n");

        foreach (var _ in containingTypes)
        {
            source.Append("}\n");
        }

        if (!component.ContainingNamespace.IsGlobalNamespace)
        {
            source.Append("}\n");
        }

        var hintName = component.ToDisplayString()
            .Replace("global::", string.Empty)
            .Replace('<', '_')
            .Replace('>', '_')
            .Replace('.', '_')
            .Replace('+', '_');
        context.AddSource($"{hintName}.VxParameters.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static ImmutableArray<INamedTypeSymbol> GetContainingTypes(INamedTypeSymbol component)
    {
        var types = new Stack<INamedTypeSymbol>();
        for (var current = component; current is not null; current = current.ContainingType)
        {
            types.Push(current);
        }

        return types.ToImmutableArray();
    }

    private static bool IsPartial(INamedTypeSymbol type)
    {
        return type.DeclaringSyntaxReferences
            .Select(static reference => reference.GetSyntax())
            .OfType<ClassDeclarationSyntax>()
            .Any(static declaration => declaration.Modifiers.Any(SyntaxKind.PartialKeyword));
    }

    private static string EscapeIdentifier(string identifier)
    {
        return SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None ? identifier : "@" + identifier;
    }
}